#!/bin/sh
java -classpath /usr/class/cs143/cool/lib/java-cup-11a.jar:/usr/class/cs143/cool/lib/jlex.jar:.:/usr/java/lib/rt.jar:/home/ygy/IdeaProjects/lexer/src/main/java/:`dirname $0` me.ygy.compiler.lexer.Lexer $*
